// =============================================================================
// MIRRORED FROM caiioo-ai/caiioo @ 40e60eae105023da15cdbcaf9b2a44d70843a3ab
// Source path: cloud/relay/src/user-relay.ts
// Mirrored at: 2026-08-12T22:56:48Z
//
// This file is auto-generated by the mirror-transparency workflow.
// Do not edit here. Changes must land in the private monorepo first.
// See README.md and ARCHITECTURE.md for the why.
// =============================================================================

/**
 * User Relay Durable Object
 *
 * Manages WebSocket connections for a single user.
 * Routes messages between the user's server(s) and client devices.
 * Supports multiple server connections with priority-based primary election.
 * Handles E2E encrypted messages (opaque to relay) and key exchange.
 */

import { pickPrimary } from './election'
import { DurableObject } from 'cloudflare:workers'
import type { RuntimeTarget } from '../../../src/shared/tier-config'
import { Conductor, type ConductorStorage } from './conductor'
import { isUserIdPinViolation } from './user-id-pin'
import {
  parseSyncWake,
  stampSyncWakeSource,
} from '../../../src/shared/cloud-sync/sync-wake'
import {
  buildFleetLanEndpointsMessage,
  sanitizeLanSyncAdvert,
  type LanSyncEndpointAdvert,
} from '../../../src/shared/cloud-sync/lan-hub-advertise'
import {
  parseSyncHotPut,
  parseSyncHotGet,
  buildSyncHotNotify,
  mergeHotMailbox,
  filterMailboxByKeys,
  type HotMailboxItem,
  SYNC_HOT_RESULT_TYPE,
} from '../../../src/shared/cloud-sync/sync-hot-mailbox'

// ============================================================================
// Types
// ============================================================================

interface ConnectionMetadata {
  userId: string
  connectionType: 'server' | 'client'
  deviceId: string
  deviceName: string
  serverType?: string
  /** Optional LAN private-sync hub host (RFC1918 only — validated on DO). */
  lanSyncHost?: string
  lanSyncPort?: number
}

interface ServerEntry {
  deviceId: string
  deviceName: string
  priority: number
  connectedAt: number
  /** Protocol generation declared at connect (gen param); legacy builds = 0. */
  generation?: number
  lastHeartbeatAt: number // Updated when DO receives PING from this server
  /** Advertised LAN sync endpoint (prefer-LAN private sync). */
  lanSyncHost?: string
  lanSyncPort?: number
}

interface ClientConnection {
  deviceId: string
  deviceName: string
  connectedAt: number
  lastActivity: number
}

interface QueuedMessage {
  payload: string
  sourceDevice: string
  timestamp: number
}

interface KeyExchangeEnvelope {
  version: 1
  type: 'key_exchange'
  publicKey: string
  deviceId: string
  deviceName: string
  timestamp: number
}

// ============================================================================
// Constants
// ============================================================================

const SERVER_PRIORITY: Record<string, number> = { desktop: 10, extension: 5, mobile: 5 }
const DEFAULT_SERVER_PRIORITY = 5

// ============================================================================
// Durable Object
// ============================================================================

export class UserRelay extends DurableObject {
  // Multi-server connections (priority-ranked)
  private servers = new Map<string, ServerEntry>()
  private primaryServerId: string | null = null
  private readonly SERVER_HEALTH_TIMEOUT_MS = 45_000

  // Client connections (mobile apps, web)
  private clients: Map<string, ClientConnection> = new Map()

  // Server's key exchange (for forwarding to new clients — from primary server only)
  private serverKeyExchange: KeyExchangeEnvelope | null = null

  // Per-device key announces. Multiple servers (desktop sidecar + extension
  // relays) have DIFFERENT E2E identities; a single cache slot let a transient
  // primary's announce poison the bootstrap key for every later client
  // (2026-07-22 "Cipher job failed" loop). Clients must always be handed the
  // CURRENT primary's key.
  private serverKeyExchanges = new Map<string, KeyExchangeEnvelope>()

  // Message queue for when no server is online
  private messageQueue: QueuedMessage[] = []
  private readonly MAX_QUEUE_SIZE = 100
  private readonly QUEUE_TTL_MS = 5 * 60 * 1000 // 5 minutes

  // Private Agents: the device + run register. Holds SEALED continuations it
  // cannot read and decides which of the user's own devices may open one next.
  // See tasks/backlog-private-agents.md. Everything it stores is already scoped
  // to one user by idFromName(userId), same as the rest of this object.
  private conductor: Conductor

  /**
   * Hot private-sync mailbox: short-TTL opaque ciphertext for peers.
   * Never decrypt; prune on access. Not a durable store.
   */
  private hotMailbox: HotMailboxItem[] = []

  constructor(ctx: DurableObjectState, env: unknown) {
    super(ctx, env)

    this.conductor = new Conductor(this.ctx.storage as unknown as ConductorStorage)

    // Auto-respond to PING messages without waking the DO from hibernation.
    // Chrome MV3 service workers go to sleep after ~30s, killing their heartbeat
    // setInterval. Without auto-response, the DO sees no activity and Cloudflare
    // closes the WebSocket with code 1006. This keeps connections alive.
    try {
      this.ctx.setWebSocketAutoResponse(
        new WebSocketRequestResponsePair(
          JSON.stringify({ type: 'PING' }),
          JSON.stringify({ type: 'PONG', timestamp: 0 })
        )
      )
    } catch (error) {
      console.error('[UserRelay] setWebSocketAutoResponse failed:', error)
    }

    // Restore state from storage on wake
    this.ctx.blockConcurrencyWhile(async () => {
      try {
        const [queue, keyExchange, perDeviceKx] = await Promise.all([
          this.ctx.storage.get<QueuedMessage[]>('messageQueue'),
          this.ctx.storage.get<KeyExchangeEnvelope>('serverKeyExchange'),
          this.ctx.storage.list<KeyExchangeEnvelope>({ prefix: 'serverKeyExchange:' }),
        ])

        if (queue) {
          const now = Date.now()
          this.messageQueue = queue.filter(
            (m) => now - m.timestamp < this.QUEUE_TTL_MS
          )
        }

        if (keyExchange) {
          this.serverKeyExchange = keyExchange
        }

        if (perDeviceKx) {
          for (const [key, envelope] of perDeviceKx) {
            this.serverKeyExchanges.set(key.slice('serverKeyExchange:'.length), envelope)
          }
        }

      } catch (error) {
        console.error('[UserRelay] Failed to restore state from storage:', error)
      }
    })
  }

  // ============================================================================
  // WebSocket Handling
  // ============================================================================

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url)

    // HTTP POST from Cloudflare Worker — forward to server WebSocket
    if (request.method === 'POST' && url.pathname === '/messaging-webhook') {
      return this.handleWebhookForward(request)
    }

    // Conductor request/reply — the door iOS/Android/desktop use. Must be
    // matched BEFORE the upgrade branch, which treats anything else as a
    // WebSocket handshake.
    if (request.method === 'POST' && url.pathname === '/pa') {
      return this.handleConductorHttp(request)
    }

    // WebSocket upgrade — existing behavior
    const metadata: ConnectionMetadata = JSON.parse(
      request.headers.get('X-Connection-Metadata') || '{}'
    )

    // SG4 (defense-in-depth) — pin this DO to its first userId and reject any
    // foreign userId. The Worker addresses us by idFromName(userId), so every
    // connection here is guaranteed to share one verified userId; this makes the
    // single-tenant invariant explicit and fail-closed against a routing bug or
    // a future refactor that bypasses idFromName.
    const pinnedUserId = await this.ctx.storage.get<string>('pinnedUserId')
    if (isUserIdPinViolation(pinnedUserId, metadata.userId)) {
      console.error(
        `[UserRelay] REJECTED cross-user connection: pinned=${pinnedUserId} incoming=${metadata.userId} type=${metadata.connectionType} device=${metadata.deviceId}`
      )
      return new Response('Forbidden: user mismatch', { status: 403 })
    }
    if (!pinnedUserId && metadata.userId) {
      await this.ctx.storage.put('pinnedUserId', metadata.userId)
    }

    // Create WebSocket pair
    const { 0: clientSocket, 1: serverSocket } = new WebSocketPair()

    if (metadata.connectionType === 'server') {
      await this.handleServerConnection(serverSocket, metadata)
    } else {
      await this.handleClientConnection(serverSocket, metadata)
    }

    return new Response(null, { status: 101, webSocket: clientSocket })
  }

  /**
   * Forward a messaging webhook payload to the user's local server.
   * If server is offline, queue the message (existing queue mechanism).
   */
  private async handleWebhookForward(request: Request): Promise<Response> {
    try {
      // M3: Check payload size before parsing
      const contentLength = parseInt(request.headers.get('Content-Length') || '0', 10)
      if (contentLength > 256 * 1024) {
        console.warn(`[UserRelay] Rejecting oversized webhook forward: ${contentLength} bytes`)
        return new Response('Payload too large', { status: 413 })
      }

      const data = await request.json() as Record<string, unknown>

      console.log(`[UserRelay] Webhook forward: servers=${this.servers.size}, primaryId=${this.primaryServerId}, recovering...`)
      const primarySocket = this.getPrimaryServer()
      console.log(`[UserRelay] Webhook forward: primarySocket=${primarySocket ? 'found' : 'null'}, servers after recovery=${this.servers.size}`)

      if (primarySocket && this.primaryServerId) {
        // Send to primary server only — NOT broadcast to all servers.
        // Broadcasting caused duplicate webhook processing when multiple servers
        // (e.g., desktop + extension) were connected simultaneously.
        this.sendToServerById(this.primaryServerId, data)
      } else {
        // Queue for delivery when server reconnects
        console.warn(`[UserRelay] No primary server — queuing webhook (queue size: ${this.messageQueue.length + 1})`)
        this.messageQueue.push({
          payload: JSON.stringify(data),
          sourceDevice: 'webhook',
          timestamp: Date.now(),
        })
        await this.ctx.storage.put('messageQueue', this.messageQueue)
      }

      return new Response('OK', { status: 200 })
    } catch (error) {
      console.error('[UserRelay] Webhook forward error:', error)
      return new Response('Internal error', { status: 500 })
    }
  }

  /**
   * Handle server connection (from user's local machine or extension).
   * Multiple servers can connect simultaneously; primary is elected by priority.
   */
  private async handleServerConnection(
    socket: WebSocket,
    metadata: ConnectionMetadata
  ): Promise<void> {
    const priority = metadata.serverType
      ? (SERVER_PRIORITY[metadata.serverType] ?? DEFAULT_SERVER_PRIORITY)
      : DEFAULT_SERVER_PRIORITY
    const generation = Number(metadata.generation) || 0

    // Remove in-memory entry for this device (will be recreated below).
    // Do NOT close old sockets — after Worker deploys, closing stale hibernation
    // sockets can cascade and kill the new socket (code 1006). Let stale sockets
    // die naturally via Cloudflare's idle timeout.
    this.servers.delete(metadata.deviceId)

    const now = Date.now()

    // Accept the WebSocket with tags for identification and hibernation recovery
    this.ctx.acceptWebSocket(socket, ['server', `priority:${priority}`, `device:${metadata.deviceId}`])

    // Create server entry (optional LAN sync hub advertisement)
    const lanAdvert = sanitizeLanSyncAdvert({
      deviceId: metadata.deviceId,
      host: metadata.lanSyncHost || '',
      port: metadata.lanSyncPort,
      label: metadata.deviceName,
    })
    const entry: ServerEntry = {
      deviceId: metadata.deviceId,
      deviceName: metadata.deviceName,
      priority,
      connectedAt: now,
      ...(generation > 0 ? { generation } : {}),
      lastHeartbeatAt: now, // Grace period for fresh connections
      ...(lanAdvert
        ? { lanSyncHost: lanAdvert.host, lanSyncPort: lanAdvert.port }
        : {}),
    }
    this.servers.set(metadata.deviceId, entry)

    // Elect primary (may change if new server has higher priority)
    this.electPrimary()

    // If new server is primary, flush queued messages
    if (this.primaryServerId === metadata.deviceId) {
      await this.flushQueueToServer()
    }

    // Notify all clients that server is connected. primaryDeviceId is the
    // conversation-primary reachability signal (backlog §2.5) — clients need
    // to know WHICH host is online, not only that one is.
    this.broadcastToClients({
      type: 'SERVER_STATUS',
      connected: true,
      connectedAt: now,
      primaryDeviceId: this.primaryServerId,
    })

    // Prefer-LAN: broadcast current LAN hub endpoints to all peers
    this.broadcastFleetLanEndpoints()

    console.log(`[UserRelay] Server connected: ${metadata.deviceId} (type=${metadata.serverType ?? 'unknown'}, priority=${priority}, isPrimary=${this.primaryServerId === metadata.deviceId}, lan=${lanAdvert ? `${lanAdvert.host}:${lanAdvert.port}` : 'none'})`)

    // No keepalive alarm — let the DO hibernate freely. The WebSocket survives
    // hibernation via Cloudflare's Hibernation API. When a webhook arrives, the
    // HTTP POST wakes the DO, getWebSockets('server') recovers the socket, and
    // the message is forwarded. The JSON PING auto-response keeps the socket in
    // hibernation storage without waking the DO.
  }

  /**
   * Handle client connection (mobile app, web)
   */
  private async handleClientConnection(
    socket: WebSocket,
    metadata: ConnectionMetadata
  ): Promise<void> {
    const client: ClientConnection = {
      deviceId: metadata.deviceId,
      deviceName: metadata.deviceName,
      connectedAt: Date.now(),
      lastActivity: Date.now(),
    }

    this.clients.set(metadata.deviceId, client)

    // Accept the WebSocket with tags for identification
    this.ctx.acceptWebSocket(socket, ['client', metadata.deviceId])

    // Determine whether a server is present. getPrimaryServer() triggers
    // hibernation recovery as a side effect, but it can momentarily return null
    // during recovery or while the server is mid-reconnect (e.g. just after a
    // Worker deploy). Fall back to a hibernation-safe socket count so we don't
    // under-report server presence and strand the client.
    let serverSocketCount = 0
    try {
      serverSocketCount = this.ctx.getWebSockets('server').length
    } catch {
      /* getWebSockets can throw during eviction */
    }
    const serverConnected = this.getPrimaryServer() !== null || serverSocketCount > 0
    const primaryEntry = this.primaryServerId ? this.servers.get(this.primaryServerId) : null

    // Send current server status directly on the socket reference
    // (don't use sendToClient — getWebSockets may not find it immediately after accept)
    try {
      socket.send(JSON.stringify({
        type: 'SERVER_STATUS',
        connected: serverConnected,
        connectedAt: primaryEntry?.connectedAt ?? null,
        primaryDeviceId: this.primaryServerId,
      }))
    } catch (error) {
      console.error(`[UserRelay] Failed to send initial status to ${metadata.deviceId}:`, error)
    }

    // Send the server's cached key so the client can start the E2E handshake
    // IMMEDIATELY. We send whenever a server socket exists AND a key is cached —
    // not only when primary election has completed — because gating on
    // getPrimaryServer() alone leaves a client that connects in a recovery /
    // mid-reconnect window waiting ~30s for the next server re-announce. The key
    // is valid (a server announced it) and the client's reply routes to the
    // server, waking it from hibernation if needed.
    // Prefer the CURRENT primary's key — the legacy single-slot cache could
    // hold a transient primary's (e.g. extension relay) identity, which made
    // every later client encrypt to the wrong server ("Cipher job failed").
    const bootstrapKx =
      (this.primaryServerId ? this.serverKeyExchanges.get(this.primaryServerId) : null) ??
      this.serverKeyExchange
    if (serverConnected && bootstrapKx) {
      try {
        socket.send(JSON.stringify({
          type: 'KEY_EXCHANGE_RESPONSE',
          keyExchange: bootstrapKx,
        }))
      } catch (error) {
        console.error(`[UserRelay] Failed to send key exchange to ${metadata.deviceId}:`, error)
      }
    }

    // Notify all servers of new client
    if (this.getPrimaryServer()) {
      this.sendToAllServers({
        type: 'CLIENT_CONNECTED',
        deviceId: metadata.deviceId,
        deviceName: metadata.deviceName,
      })
    }

    console.log(`[UserRelay] Client connected: ${metadata.deviceId}`)
  }

  // ============================================================================
  // Message Handling
  // ============================================================================

  /**
   * Called by Cloudflare when WebSocket message received
   */
  async webSocketMessage(
    ws: WebSocket,
    message: string | ArrayBuffer
  ): Promise<void> {
    let tags: string[]
    try {
      tags = this.ctx.getTags(ws)
    } catch {
      // Dead socket after hibernation — ignore
      return
    }
    const isServer = tags.includes('server')

    if (typeof message !== 'string') {
      message = new TextDecoder().decode(message)
    }

    try {
      const data = JSON.parse(message)

      // Private Agent traffic terminates HERE, before the server/client split.
      // Both connection types are runners — a desktop connects as `server` and
      // a phone as `client` — and none of it may be forwarded: lease traffic
      // delivered to another device's agent loop would be nonsense at best.
      if (typeof data?.type === 'string' && data.type.startsWith('PA_')) {
        await this.handleConductorMessage(data, ws, tags, isServer)
        return
      }

      // SYNC_WAKE: metadata-only private-sync tempo nudge. Fan out to every
      // other connection on this user DO; never store the payload (no plaintext
      // thread ids — only optional HMAC blinds). See sync-wake.ts.
      if (data?.type === 'SYNC_WAKE') {
        this.handleSyncWakeMessage(data, tags, isServer, ws)
        return
      }

      // Prefer-LAN hub: server updates its advertised LAN sync endpoint.
      if (data?.type === 'LAN_SYNC_ENDPOINT' && isServer) {
        this.handleLanSyncEndpointUpdate(data, tags)
        return
      }

      // Hot private-sync mailbox (opaque ciphertext, short TTL).
      if (data?.type === 'SYNC_HOT_PUT') {
        this.handleSyncHotPut(data, tags, isServer, ws)
        return
      }
      if (data?.type === 'SYNC_HOT_GET') {
        this.handleSyncHotGet(data, tags, isServer, ws)
        return
      }

      if (isServer) {
        // Restore in-memory server map after hibernation wake-up
        if (this.servers.size === 0) {
          this.recoverServersFromHibernation()
        }
        await this.handleServerMessage(data, ws, tags)
      } else {
        const deviceId = tags.find((t) => t !== 'client') || 'unknown'
        await this.handleClientMessage(data, deviceId)
      }
    } catch (error) {
      console.error('[UserRelay] Message handling error:', error)
    }
  }

  // ============================================================================
  // Private sync tempo — SYNC_WAKE fan-out (metadata only, not stored)
  // ============================================================================

  /**
   * Fan SYNC_WAKE to every other connection for this user so peers snap-poll
   * private sync. Origin device id is taken from socket TAGS (never trust body).
   * Payload is not persisted — the DO is a bus, not a log.
   */
  private handleSyncWakeMessage(
    data: Record<string, unknown>,
    tags: string[],
    isServer: boolean,
    originWs: WebSocket,
  ): void {
    const parsed = parseSyncWake(data)
    if (!parsed) {
      console.warn('[UserRelay] Dropped invalid SYNC_WAKE')
      return
    }

    const sourceDeviceId = isServer
      ? this.findServerDeviceIdByTags(tags) || tags.find((t) => t.startsWith('device:'))?.slice(7)
      : tags.find((t) => t !== 'client')

    if (!sourceDeviceId) {
      console.warn('[UserRelay] SYNC_WAKE without identifiable device — drop')
      return
    }

    const stamped = stampSyncWakeSource(parsed, sourceDeviceId)
    const message = JSON.stringify(stamped)
    let delivered = 0

    const fan = (sockets: WebSocket[]) => {
      for (const socket of sockets) {
        if (socket === originWs) continue
        try {
          socket.send(message)
          delivered++
        } catch {
          /* dead socket */
        }
      }
    }

    try {
      fan(this.ctx.getWebSockets('server'))
    } catch {
      /* hibernation */
    }
    try {
      fan(this.ctx.getWebSockets('client'))
    } catch {
      /* hibernation */
    }

    console.log(
      `[UserRelay] SYNC_WAKE fan-out from ${sourceDeviceId} reason=${stamped.reason} delivered≈${delivered}`,
    )
  }

  // ============================================================================
  // Prefer-LAN hub advertisement + hot mailbox
  // ============================================================================

  private collectLanEndpoints(): LanSyncEndpointAdvert[] {
    const out: LanSyncEndpointAdvert[] = []
    for (const s of this.servers.values()) {
      const a = sanitizeLanSyncAdvert({
        deviceId: s.deviceId,
        host: s.lanSyncHost || '',
        port: s.lanSyncPort,
        label: s.deviceName,
      })
      if (a) out.push(a)
    }
    return out
  }

  private broadcastFleetLanEndpoints(): void {
    const msg = buildFleetLanEndpointsMessage(this.collectLanEndpoints())
    const payload = JSON.stringify(msg)
    const fan = (sockets: WebSocket[]) => {
      for (const socket of sockets) {
        try {
          socket.send(payload)
        } catch {
          /* dead */
        }
      }
    }
    try {
      fan(this.ctx.getWebSockets('server'))
    } catch {
      /* hibernation */
    }
    try {
      fan(this.ctx.getWebSockets('client'))
    } catch {
      /* hibernation */
    }
  }

  private handleLanSyncEndpointUpdate(
    data: Record<string, unknown>,
    tags: string[],
  ): void {
    const deviceId =
      this.findServerDeviceIdByTags(tags) ||
      tags.find((t) => t.startsWith('device:'))?.slice(7)
    if (!deviceId) return
    const entry = this.servers.get(deviceId)
    if (!entry) return
    const advert = sanitizeLanSyncAdvert({
      deviceId,
      host: typeof data.host === 'string' ? data.host : '',
      port: typeof data.port === 'number' ? data.port : undefined,
      label: entry.deviceName,
    })
    if (advert) {
      entry.lanSyncHost = advert.host
      entry.lanSyncPort = advert.port
    } else {
      delete entry.lanSyncHost
      delete entry.lanSyncPort
    }
    this.servers.set(deviceId, entry)
    this.broadcastFleetLanEndpoints()
  }

  private handleSyncHotPut(
    data: Record<string, unknown>,
    tags: string[],
    isServer: boolean,
    originWs: WebSocket,
  ): void {
    const parsed = parseSyncHotPut(data)
    if (!parsed) {
      console.warn('[UserRelay] Dropped invalid SYNC_HOT_PUT')
      return
    }
    const sourceDeviceId = isServer
      ? this.findServerDeviceIdByTags(tags) ||
        tags.find((t) => t.startsWith('device:'))?.slice(7)
      : tags.find((t) => t !== 'client')
    this.hotMailbox = mergeHotMailbox(this.hotMailbox, parsed.items)
    const notify = buildSyncHotNotify({
      keys: parsed.items.map((i) => i.key),
      sourceDeviceId: sourceDeviceId || undefined,
      sentAt: Date.now(),
    })
    const message = JSON.stringify(notify)
    const fan = (sockets: WebSocket[]) => {
      for (const socket of sockets) {
        if (socket === originWs) continue
        try {
          socket.send(message)
        } catch {
          /* dead */
        }
      }
    }
    try {
      fan(this.ctx.getWebSockets('server'))
    } catch {
      /* */
    }
    try {
      fan(this.ctx.getWebSockets('client'))
    } catch {
      /* */
    }
    console.log(
      `[UserRelay] SYNC_HOT_PUT stored=${parsed.items.length} mailbox=${this.hotMailbox.length}`,
    )
  }

  private handleSyncHotGet(
    data: Record<string, unknown>,
    tags: string[],
    isServer: boolean,
    originWs: WebSocket,
  ): void {
    const parsed = parseSyncHotGet(data)
    if (!parsed) return
    const now = Date.now()
    this.hotMailbox = mergeHotMailbox(this.hotMailbox, [], now)
    const items = filterMailboxByKeys(this.hotMailbox, parsed.keys, now)
    try {
      originWs.send(
        JSON.stringify({
          type: SYNC_HOT_RESULT_TYPE,
          items,
          ...(parsed.requestId ? { requestId: parsed.requestId } : {}),
        }),
      )
    } catch {
      /* dead socket */
    }
  }

  // ============================================================================
  // Private Agents — conductor routing
  // ============================================================================

  /**
   * Route one Private Agent message to the conductor and answer on the same
   * socket.
   *
   * The device id comes from the socket's TAGS, never from the payload — a
   * client-supplied deviceId would let one device claim, commit to, or release
   * another's lease, which is the entire exclusion guarantee. Same reasoning as
   * `metadata.userId` always being the verified token subject
   * (`.claude/rules/remote-relay-isolation.md`).
   */
  private async handleConductorMessage(
    data: Record<string, unknown>,
    ws: WebSocket,
    tags: string[],
    isServer: boolean,
  ): Promise<void> {
    const deviceId = isServer
      ? this.findServerDeviceIdByTags(tags)
      : tags.find((t) => t !== 'client')
    const requestId = typeof data.requestId === 'string' ? data.requestId : ''

    const payload = await this.dispatchConductorMessage(data, deviceId)

    try {
      ws.send(JSON.stringify({ type: 'PA_RESULT', requestId, ...payload }))
    } catch {
      /* socket died mid-reply — the lease expiry path covers it */
    }
  }

  /**
   * The conductor's HTTP door — one POST, one PA_RESULT, no held connection.
   *
   * The socket path is only ever held by the relay.caiioo.ai web client, so
   * iOS, Android, macOS and Tauri — the runtimes cross-device handoff exists
   * FOR — had no way to reach the conductor at all. Holding a socket open on a
   * phone to wait for a lease it may never be offered costs battery and a
   * reconnect story on every runtime, to save a poll interval on an event that
   * happens a few times a day.
   *
   * It shares `dispatchConductorMessage` and the same storage with the socket
   * path deliberately: a second implementation would be a second set of fencing
   * rules, and mutual exclusion across devices is the entire guarantee here.
   *
   * Device identity comes from the `X-PA-Device` HEADER, never the body —
   * the same connection-level channel the socket path reads its tag from
   * (invariant 2). The SG4 user pin below is applied exactly as on the upgrade
   * path, so a routing bug fails closed rather than crossing users.
   */
  private async handleConductorHttp(request: Request): Promise<Response> {
    const json = (payload: Record<string, unknown>, status = 200): Response =>
      new Response(JSON.stringify(payload), {
        status,
        headers: { 'Content-Type': 'application/json' },
      })

    let userId: string | undefined
    try {
      userId = JSON.parse(request.headers.get('X-Connection-Metadata') || '{}').userId
    } catch {
      return json({ ok: false, reason: 'bad-metadata' }, 400)
    }

    const pinnedUserId = await this.ctx.storage.get<string>('pinnedUserId')
    if (isUserIdPinViolation(pinnedUserId, userId)) {
      console.error(
        `[UserRelay] REJECTED cross-user conductor POST: pinned=${pinnedUserId} incoming=${userId}`
      )
      return new Response('Forbidden: user mismatch', { status: 403 })
    }
    if (!pinnedUserId && userId) {
      await this.ctx.storage.put('pinnedUserId', userId)
    }

    let data: Record<string, unknown>
    try {
      data = (await request.json()) as Record<string, unknown>
    } catch {
      return json({ type: 'PA_RESULT', ok: false, reason: 'bad-request' }, 400)
    }

    const requestId = typeof data?.requestId === 'string' ? data.requestId : ''
    const deviceId = request.headers.get('X-PA-Device') || undefined
    const payload = await this.dispatchConductorMessage(data ?? {}, deviceId)

    return json({ type: 'PA_RESULT', requestId, ...payload })
  }

  /**
   * Route one Private Agent message to the conductor and return the answer.
   *
   * Transport-free on purpose — the WebSocket and HTTP doors both call this, so
   * the lease protocol has exactly one implementation.
   *
   * The device id is supplied by the CALLER from connection metadata (a socket
   * tag or a header), never read out of `data` — a payload-supplied deviceId
   * would let one connection claim, commit to, or release another's lease,
   * which is the entire exclusion guarantee. Same reasoning as `metadata.userId`
   * always being the verified token subject
   * (`.claude/rules/remote-relay-isolation.md`).
   */
  private async dispatchConductorMessage(
    data: Record<string, unknown>,
    deviceId: string | undefined,
  ): Promise<Record<string, unknown>> {
    if (!deviceId) {
      return { ok: false, reason: 'unidentified-device' }
    }

    try {
      switch (data.type) {
        case 'PA_REGISTER': {
          const devices = await this.conductor.registerDevice({
            deviceId,
            // The device reports which runtime it IS; its class and its
            // eligibility both derive from that, so there is no second field
            // for it to contradict.
            runtime: data.runtime as RuntimeTarget,
            ...(data.powerHint ? { powerHint: data.powerHint as 'active' | 'background' | 'plugged' } : {}),
            ...(data.wakeToken ? { wakeToken: String(data.wakeToken) } : {}),
          })
          return { ok: true, devices }
        }

        case 'PA_LIST_DEVICES':
          return { ok: true, devices: await this.conductor.listDevices() }

        case 'PA_LIST_RUNS':
          return {
            ok: true,
            runs: await this.conductor.listRuns(
              typeof data.threadBlind === 'string' ? data.threadBlind : undefined,
            ),
          }

        case 'PA_OFFER': {
          const result = await this.conductor.offerRun({
            runId: String(data.runId),
            threadBlind: String(data.threadBlind),
            requires: Number(data.requires) || 0,
            continuation: data.continuation as string[],
          })
          return { ok: true, ...result }
        }

        case 'PA_CLAIM': {
          const run = await this.conductor.claimRun(
            deviceId,
            typeof data.runId === 'string' ? data.runId : undefined,
          )
          // null is "nothing for you right now", not a failure — a runner polls
          // this and an error would make an idle poll look like a fault.
          return { ok: true, run }
        }

        case 'PA_CANCEL_THREAD': {
          const threadBlind = typeof data.threadBlind === 'string' ? data.threadBlind : ''
          if (!threadBlind) return { ok: false, reason: 'missing-thread-blind' }
          return {
            ok: true,
            cancelled: await this.conductor.cancelThreadRuns(threadBlind),
          }
        }

        case 'PA_COMMIT': {
          const result = await this.conductor.commitRun({
            runId: String(data.runId),
            deviceId,
            epoch: Number(data.epoch),
            expectedSeq: Number(data.expectedSeq),
            continuation: data.continuation as string[],
            ...(data.status ? { status: data.status as 'running' | 'done' | 'failed' } : {}),
            ...(data.steps !== undefined ? { steps: Number(data.steps) } : {}),
            ...(data.pinTo ? { pinTo: String(data.pinTo) } : {}),
            ...(data.requires !== undefined ? { requires: Number(data.requires) } : {}),
          })
          return result.ok ? { ok: true, seq: result.seq } : { ok: false, reason: result.reason }
        }

        case 'PA_HEARTBEAT':
        case 'PA_RELEASE': {
          const ref = { deviceId, epoch: Number(data.epoch) }
          const result =
            data.type === 'PA_RELEASE'
              ? await this.conductor.releaseRun(String(data.runId), ref)
              : await this.conductor.heartbeatRun(String(data.runId), ref)
          return result.ok ? { ok: true, seq: result.seq } : { ok: false, reason: result.reason }
        }

        default:
          return { ok: false, reason: 'unknown-type' }
      }
    } catch (error) {
      // A rejected offer/commit (oversized or empty continuation) is a normal
      // client error. Answering it keeps the runner's request loop alive; an
      // unanswered request would hang until its own timeout.
      console.error('[UserRelay] Conductor error:', error)
      return { ok: false, reason: error instanceof Error ? error.message : 'conductor-error' }
    }
  }

  /**
   * Alarm handler — the lease reaper, and nothing else.
   *
   * Deliberately does NOT run agent work: a Cloudflare alarm caps at 15 minutes
   * per invocation, which would be a real constraint for a cloud runner and is
   * irrelevant for a referee. Recovering a dead runner's lease is milliseconds.
   */
  async alarm(): Promise<void> {
    try {
      await this.conductor.reap()
    } catch (error) {
      console.error('[UserRelay] Conductor reap failed:', error)
    }
  }

  /**
   * Handle message from server
   */
  private async handleServerMessage(
    data: Record<string, unknown>,
    ws: WebSocket,
    tags: string[]
  ): Promise<void> {
    const { type, targetDevice } = data

    switch (type) {
      case 'SERVER_KEY_ANNOUNCE': {
        const senderDeviceId = this.findServerDeviceIdByTags(tags)

        // Always remember which key belongs to which server device — clients
        // are bootstrapped with the CURRENT primary's key, so a non-primary
        // announce must be retained (its owner may become primary later) but
        // must never overwrite the bootstrap key.
        if (senderDeviceId) {
          this.serverKeyExchanges.set(senderDeviceId, data.keyExchange as KeyExchangeEnvelope)
          this.ctx.storage
            .put(`serverKeyExchange:${senderDeviceId}`, data.keyExchange)
            .catch((e) => console.error('[UserRelay] Failed to persist per-device key:', e))
        }

        if (senderDeviceId === this.primaryServerId) {
          this.serverKeyExchange = data.keyExchange as KeyExchangeEnvelope
          await this.ctx.storage.put('serverKeyExchange', this.serverKeyExchange)
          console.log('[UserRelay] Server key exchange stored (from primary)')

          // Push the key to every connected client. A client that connected
          // BEFORE the server was visible (server mid-reconnect after a 1006, or
          // a hibernation gap) waits passively for KEY_EXCHANGE_RESPONSE and
          // never announces its own key — so without this broadcast it would
          // wait forever ("Cannot send - session not established") even though
          // the server is now up. Re-announcing on every server (re)connect is
          // correct: a reconnected server has no session state for existing
          // clients, so they SHOULD re-handshake.
          this.broadcastToClients({
            type: 'KEY_EXCHANGE_RESPONSE',
            keyExchange: this.serverKeyExchange,
          })
        }
        return
      }

      case 'KEY_EXCHANGE_RESPONSE':
        // Server responding to specific client's key exchange
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, data)
        }
        return

      case 'KEY_ROTATION_REQUEST':
      case 'KEY_ROTATION_ACK':
        // Key rotation messages - forward to specific client
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, data)
        }
        return

      case 'ENCRYPTED':
        // Encrypted message to specific client (we can't read it)
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, {
            type: 'ENCRYPTED',
            payload: data.payload,
          })
        }
        return

      case 'REQUEST_KEY_EXCHANGE':
        // Server asking client to re-key
        if (typeof targetDevice === 'string') {
          this.sendToClient(targetDevice, data)
        }
        return

      case 'BROADCAST':
        // Server broadcasting to all clients (still encrypted per-client)
        // This is just metadata, each message is individually encrypted
        this.broadcastToClients(data.payload as Record<string, unknown>)
        return

      case 'PING': {
        // Server heartbeat — find which server sent it, update health
        const senderDeviceId = this.findServerDeviceIdBySocket(ws)
        if (senderDeviceId) {
          const entry = this.servers.get(senderDeviceId)
          if (entry) {
            entry.lastHeartbeatAt = Date.now()
          }
          // Re-elect in case a previously unhealthy server recovered
          this.electPrimary()
        }
        this.sendToServerSocket(ws, { type: 'PONG', timestamp: Date.now() })
        return
      }

      default:
        console.warn(`[UserRelay] Unknown server message type: ${type}`)
    }
  }

  /**
   * Handle message from client
   */
  private async handleClientMessage(
    data: Record<string, unknown>,
    sourceDevice: string
  ): Promise<void> {
    const { type } = data

    // Update last activity
    const client = this.clients.get(sourceDevice)
    if (client) {
      client.lastActivity = Date.now()
    }

    switch (type) {
      case 'PING':
        // Connection health check
        this.sendToClient(sourceDevice, {
          type: 'PONG',
          timestamp: Date.now(),
        })
        return

      case 'GET_DEVICES':
        // Client requesting list of connected devices
        this.sendToClient(sourceDevice, {
          type: 'CONNECTED_DEVICES',
          devices: this.getConnectedDevices(),
          serverConnected: this.getPrimaryServer() !== null,
        })
        return

      case 'KEY_EXCHANGE': {
        // Client sending its public key — forward to the PRIMARY server ONLY.
        // Broadcasting to all servers made every connected server answer with
        // its OWN identity key; the client's single session slot flip-flopped
        // between identities and the handshake never converged (2026-07-22).
        // The client puts the envelope in `keyExchange` (older clients used
        // `payload`); forward under BOTH names so any server build receives it.
        const primarySocket = this.getPrimaryServer() // triggers recovery + election
        if (primarySocket && this.primaryServerId) {
          const keyExchange = data.keyExchange ?? data.payload
          const payload = JSON.stringify({
            type: 'KEY_EXCHANGE',
            sourceDevice,
            keyExchange,
            payload: keyExchange,
          })
          // Broadcast to EVERY socket of the primary DEVICE, not one picked
          // socket: after hibernation the device can have a zombie + a live
          // socket, readyState shows OPEN on both, and socket order is not
          // guaranteed — a single-socket send sometimes hit the corpse and the
          // handshake silently died (2026-07-23 "Initializing Caiioo" hang).
          // Other server identities still never see it (convergence intact).
          try {
            const sockets = this.getWebSocketsByTags(['server', `device:${this.primaryServerId}`])
            for (const s of sockets) {
              try { s.send(payload) } catch { /* dead socket */ }
            }
          } catch (error) {
            console.error('[UserRelay] Failed to forward KEY_EXCHANGE to primary device:', error)
          }
        } else {
          this.sendToClient(sourceDevice, {
            type: 'SERVER_DISCONNECTED',
          })
        }
        return
      }

      case 'KEY_ROTATION_REQUEST':
      case 'KEY_ROTATION_ACK':
        // Key rotation messages - forward to server
        if (this.getPrimaryServer()) {
          this.sendToServer({
            type,
            sourceDevice,
            payload: data.payload,
          })
        }
        return

      case 'ENCRYPTED':
        // Encrypted message to server (we can't read it)
        if (this.getPrimaryServer()) {
          this.sendToServer({
            type: 'ENCRYPTED',
            sourceDevice,
            payload: data.payload,
          })
        } else {
          // Queue for later (still encrypted)
          await this.queueMessage(JSON.stringify(data), sourceDevice)
          this.sendToClient(sourceDevice, {
            type: 'MESSAGE_QUEUED',
            queuePosition: this.messageQueue.length,
          })
        }
        return

      default:
        console.warn(`[UserRelay] Unknown client message type: ${type}`)
    }
  }

  // ============================================================================
  // WebSocket Lifecycle
  // ============================================================================

  /**
   * Called by Cloudflare when WebSocket closes
   */
  async webSocketClose(
    ws: WebSocket,
    code: number,
    reason: string
  ): Promise<void> {
    try {
      // After hibernation wake-up on abnormal close (code 1006), getTags() can
      // throw because the WebSocket reference is already dead. Guard with try/catch.
      let tags: string[]
      try {
        tags = this.ctx.getTags(ws)
      } catch (error) {
        console.warn(`[UserRelay] getTags failed on close (code ${code}), checking server state:`, error)
        // Can't determine if this was server or client — check if any server
        // sockets remain via getWebSockets. If fewer than expected, re-recover.
        try {
          const serverSockets = this.ctx.getWebSockets('server')
          if (serverSockets.length === 0) {
            this.servers.clear()
            this.primaryServerId = null
            try {
              this.broadcastToClients({
                type: 'SERVER_STATUS',
                connected: false,
                disconnectedAt: Date.now(),
                primaryDeviceId: null,
              })
            } catch { /* clients may also be dead during DO eviction */ }
          } else {
            this.recoverServersFromHibernation()
            this.electPrimary()
          }
        } catch { /* getWebSockets can fail during eviction */ }
        return
      }

      const isServer = tags.includes('server')

      if (isServer) {
        // Find which server disconnected from device tag
        const deviceTag = tags.find(t => t.startsWith('device:'))
        const deviceId = deviceTag?.split(':')[1]

        if (deviceId) {
          // A reconnecting device leaves its STALE socket in hibernation
          // storage (handleServerConnection deliberately does not close it).
          // When that stale socket finally dies, the device's CURRENT socket
          // may still be open — deleting the entry then leaves the DO with no
          // primary while the server is healthy, stranding every remote
          // client (2026-07-22 "Still reaching your server…"). Only evict
          // when no other open socket serves this device.
          let remainingOpen = 0
          try {
            remainingOpen = this.getWebSocketsByTags(['server', `device:${deviceId}`])
              .filter((s) => s !== ws && s.readyState === 1).length
          } catch { /* getWebSockets can fail during eviction — fall through to evict */ }

          if (remainingOpen > 0) {
            console.log(`[UserRelay] Stale socket closed for ${deviceId} (code ${code} ${reason}) — ${remainingOpen} live socket(s) remain, keeping entry`)
            return
          }

          this.servers.delete(deviceId)
          console.log(`[UserRelay] Server disconnected: ${deviceId} (code ${code} ${reason})`)

          // If it was primary, re-elect
          if (this.primaryServerId === deviceId) {
            this.primaryServerId = null
            this.electPrimary()

            if (this.primaryServerId) {
              // New primary found — flush queue and notify
              console.log(`[UserRelay] New primary elected: ${this.primaryServerId}`)
              await this.flushQueueToServer()
            }
          }

          // Broadcast status update — wrapped in try/catch because during DO eviction
          // client sockets may also be dead, causing broadcastToClients to throw
          try {
            if (this.servers.size === 0) {
              this.broadcastToClients({
                type: 'SERVER_STATUS',
                connected: false,
                disconnectedAt: Date.now(),
                primaryDeviceId: null,
              })
            } else {
              const primaryEntry = this.primaryServerId ? this.servers.get(this.primaryServerId) : null
              this.broadcastToClients({
                type: 'SERVER_STATUS',
                connected: this.primaryServerId !== null,
                connectedAt: primaryEntry?.connectedAt ?? null,
                primaryDeviceId: this.primaryServerId,
              })
            }
          } catch {
            // Client sockets dead during DO eviction — ignore
          }
        }
      } else {
        const deviceId = tags.find((t) => t !== 'client')
        if (deviceId) {
          this.clients.delete(deviceId)

          // Notify all servers
          if (this.getPrimaryServer()) {
            this.sendToAllServers({
              type: 'CLIENT_DISCONNECTED',
              deviceId,
              timestamp: Date.now(),
            })
          }

          console.log(`[UserRelay] Client disconnected: ${deviceId}`)
        }
      }
    } catch (error) {
      console.error(`[UserRelay] webSocketClose handler failed (code ${code}):`, error)
    }
  }

  /**
   * Called by Cloudflare on WebSocket error
   */
  async webSocketError(ws: WebSocket, error: unknown): Promise<void> {
    console.error('[UserRelay] WebSocket error:', error)
    try {
      ws.close(1011, 'Internal error')
    } catch {
      // Socket already dead after hibernation wake-up — ignore
    }
  }

  // ============================================================================
  // Server Election
  // ============================================================================

  /**
   * Elect the primary server based on priority (highest wins),
   * with connectedAt as tiebreaker (earliest wins).
   * Servers that haven't sent a heartbeat within the health timeout are skipped.
   */
  private electPrimary(): void {
    const now = Date.now()
    // Ranking lives in election.ts (pure, tested): priority, then declared
    // GENERATION (a legacy public build can never outrank a current one),
    // then RECENCY — the old earliest-wins tiebreak let a days-old 0.9.761
    // desktop's hibernation-persistent socket beat every freshly restarted
    // current desktop forever, black-holing key exchanges and submits while
    // the fleet read "your Mac is offline" (#17, 2026-08-12).
    const bestId = pickPrimary(this.servers, (id) => {
      const entry = this.servers.get(id)
      if (!entry) return false
      // Health check. The PING auto-response answers server heartbeats
      // WITHOUT waking the DO, so lastHeartbeatAt is effectively frozen at
      // connect/recovery time — after 45s every entry looked "unhealthy" and
      // elections were random (which let extension relays beat the desktop
      // sidecar and poison the key cache, 2026-07-22). An OPEN socket for the
      // device is the primary health signal; the heartbeat window remains as
      // fallback for the rare case the socket list is unavailable.
      const heartbeatFresh = now - entry.lastHeartbeatAt <= this.SERVER_HEALTH_TIMEOUT_MS
      return this.deviceHasOpenSocket(id) || heartbeatFresh
    })

    const oldPrimary = this.primaryServerId
    this.primaryServerId = bestId

    // Notify on primary change
    if (oldPrimary !== bestId) {
      if (oldPrimary) this.sendToServerById(oldPrimary, { type: 'ROLE_CHANGE', role: 'standby' })
      if (bestId) this.sendToServerById(bestId, { type: 'ROLE_CHANGE', role: 'primary' })
      console.log(`[UserRelay] Primary server changed: ${oldPrimary ?? 'none'} -> ${bestId ?? 'none'}`)

      // Failover re-key: clients are E2E-keyed to the OLD primary's identity.
      // Push the new primary's key so they re-handshake instead of encrypting
      // to a dead identity forever.
      if (bestId) {
        const kx = this.serverKeyExchanges.get(bestId)
        if (kx) {
          this.serverKeyExchange = kx
          this.ctx.storage
            .put('serverKeyExchange', kx)
            .catch((e) => console.error('[UserRelay] Failed to persist primary key:', e))
          try {
            this.broadcastToClients({ type: 'KEY_EXCHANGE_RESPONSE', keyExchange: kx })
          } catch { /* clients may be dead during eviction */ }
        }
      }
    }
  }

  /** True when at least one OPEN WebSocket is tagged for this server device. */
  private deviceHasOpenSocket(deviceId: string): boolean {
    try {
      return this.getWebSocketsByTags(['server', `device:${deviceId}`])
        .some((s) => s.readyState === 1)
    } catch {
      return false
    }
  }

  // ============================================================================
  // Server Socket Resolution
  // ============================================================================

  /**
   * Get the primary server's WebSocket, recovering from hibernation if needed.
   * Replaces the old getServerSocket() single-socket method.
   */
  private getPrimaryServer(): WebSocket | null {
    if (!this.primaryServerId) {
      this.recoverServersFromHibernation()
      this.electPrimary()
    }
    if (!this.primaryServerId) return null

    const entry = this.servers.get(this.primaryServerId)
    if (!entry) return null

    // Find the actual socket by device tag. After deploys, multiple stale sockets
    // may exist for the same device. Pick the LAST one (most recently accepted)
    // and verify it's actually usable.
    try {
      const sockets = this.getWebSocketsByTags(['server', `device:${this.primaryServerId}`])
      // Try from newest to oldest — newest is most likely the live one
      for (let i = sockets.length - 1; i >= 0; i--) {
        const s = sockets[i]
        if (s.readyState === 1) return s // 1 = OPEN
      }
      return null
    } catch {
      return null
    }
  }

  /**
   * Recover server entries from hibernation by reading socket tags.
   * In-memory state is lost on hibernation; tags survive.
   */
  private recoverServersFromHibernation(): void {
    let serverSockets: WebSocket[]
    try {
      serverSockets = this.ctx.getWebSockets('server')
    } catch {
      return
    }
    if (serverSockets.length === 0) return

    this.servers.clear()
    for (const socket of serverSockets) {
      try {
        const tags = this.ctx.getTags(socket)
        const priorityTag = tags.find(t => t.startsWith('priority:'))
        const deviceTag = tags.find(t => t.startsWith('device:'))
        const priority = priorityTag ? parseInt(priorityTag.split(':')[1]) : DEFAULT_SERVER_PRIORITY
        const deviceId = deviceTag?.split(':')[1] ?? `recovered-${Date.now()}`

        this.servers.set(deviceId, {
          deviceId,
          deviceName: 'Recovered',
          priority,
          connectedAt: Date.now(),
          lastHeartbeatAt: Date.now(), // Grace period
        })
      } catch { /* dead socket -- skip */ }
    }
    console.log(`[UserRelay] Recovered ${this.servers.size} server(s) from hibernation`)
  }

  /**
   * Find the server deviceId that owns a given WebSocket, by matching tags.
   */
  private findServerDeviceIdByTags(tags: string[]): string | null {
    const deviceTag = tags.find(t => t.startsWith('device:'))
    return deviceTag?.split(':')[1] ?? null
  }

  /**
   * Find the server deviceId that owns a given WebSocket reference.
   * Used when we have the socket but not the tags (e.g., PING handler).
   */
  private findServerDeviceIdBySocket(ws: WebSocket): string | null {
    try {
      const tags = this.ctx.getTags(ws)
      return this.findServerDeviceIdByTags(tags)
    } catch {
      return null
    }
  }

  /**
   * Get WebSockets matching ALL specified tags.
   * CF's getWebSockets() only filters by one tag, so we filter the rest manually.
   */
  private getWebSocketsByTags(tags: string[]): WebSocket[] {
    if (tags.length === 0) return []
    try {
      // Filter by first tag via CF API, then narrow by remaining tags
      const sockets = this.ctx.getWebSockets(tags[0])
      if (tags.length === 1) return sockets
      const remainingTags = tags.slice(1)
      return sockets.filter(socket => {
        try {
          const socketTags = this.ctx.getTags(socket)
          return remainingTags.every(t => socketTags.includes(t))
        } catch {
          return false
        }
      })
    } catch {
      return []
    }
  }

  // ============================================================================
  // Message Queue
  // ============================================================================

  /**
   * Queue a message for when server comes back online
   */
  private async queueMessage(
    payload: string,
    sourceDevice: string
  ): Promise<void> {
    // Remove old messages if queue is full
    while (this.messageQueue.length >= this.MAX_QUEUE_SIZE) {
      this.messageQueue.shift()
    }

    this.messageQueue.push({
      payload,
      sourceDevice,
      timestamp: Date.now(),
    })

    // Persist queue
    await this.ctx.storage.put('messageQueue', this.messageQueue)
  }

  /**
   * Flush queued messages to server (called when server reconnects)
   */
  private async flushQueueToServer(): Promise<void> {
    if (!this.getPrimaryServer() || this.messageQueue.length === 0) return

    const now = Date.now()
    const validMessages = this.messageQueue.filter(
      (m) => now - m.timestamp < this.QUEUE_TTL_MS
    )

    for (const msg of validMessages) {
      const data = JSON.parse(msg.payload)

      // Don't spread queue metadata onto infrastructure messages --
      // MESSAGING_WEBHOOK and similar types have a defined shape that
      // must not be polluted with sourceDevice/wasQueued/timestamp.
      if (data.type === 'MESSAGING_WEBHOOK' && this.primaryServerId) {
        // Send webhooks to primary only (not broadcast) to prevent duplicate processing
        this.sendToServerById(this.primaryServerId, data)
      } else if (data.type === 'MESSAGING_WEBHOOK') {
        // Fallback: no primaryServerId but getPrimaryServer() returned non-null
        // (shouldn't happen, but safe fallback)
        this.sendToServer(data)
      } else {
        this.sendToServer({
          ...data,
          sourceDevice: msg.sourceDevice,
          timestamp: msg.timestamp,
          wasQueued: true,
        })
      }
    }

    // Clear queue
    this.messageQueue = []
    await this.ctx.storage.delete('messageQueue')

    // Notify clients
    this.broadcastToClients({
      type: 'QUEUE_FLUSHED',
      count: validMessages.length,
    })

    console.log(`[UserRelay] Flushed ${validMessages.length} queued messages`)
  }

  // ============================================================================
  // Utility Methods
  // ============================================================================

  /**
   * Send message to primary server
   */
  private sendToServer(data: unknown): void {
    // After hibernation, readyState may show OPEN on zombie sockets.
    // Broadcast to ALL server sockets — the live one receives it,
    // dead ones silently fail (Cloudflare doesn't throw on hibernated sends).
    try {
      const allServerSockets = this.ctx.getWebSockets('server')
      console.log(`[UserRelay] sendToServer: broadcasting to ${allServerSockets.length} server socket(s)`)
      const payload = JSON.stringify(data)
      for (const socket of allServerSockets) {
        try { socket.send(payload) } catch { /* dead socket */ }
      }
    } catch (error) {
      console.error('[UserRelay] Failed to send to server, queuing for retry:', error)
      this.messageQueue.push({
        payload: JSON.stringify(data),
        sourceDevice: 'retry',
        timestamp: Date.now(),
      })
      this.ctx.storage.put('messageQueue', this.messageQueue).catch(e =>
        console.error('[UserRelay] Failed to persist retry queue:', e)
      )
    }
  }

  /**
   * Send message to all connected servers (e.g., CLIENT_CONNECTED/CLIENT_DISCONNECTED)
   */
  private sendToAllServers(data: unknown): void {
    const message = JSON.stringify(data)
    let serverSockets: WebSocket[]
    try {
      serverSockets = this.ctx.getWebSockets('server')
    } catch {
      return
    }

    for (const socket of serverSockets) {
      try {
        socket.send(message)
      } catch (error) {
        console.error('[UserRelay] Failed to send to server socket:', error)
      }
    }
  }

  /**
   * Send message to a specific server by deviceId
   */
  private sendToServerById(deviceId: string, data: unknown): void {
    try {
      const sockets = this.getWebSocketsByTags(['server', `device:${deviceId}`])
      const message = JSON.stringify(data)
      for (const socket of sockets) {
        try {
          socket.send(message)
        } catch (error) {
          console.error(`[UserRelay] Failed to send to server ${deviceId}:`, error)
        }
      }
    } catch {
      // getWebSockets failed — hibernation edge case
    }
  }

  /**
   * Send message directly to a WebSocket reference (e.g., PONG response to specific server)
   */
  private sendToServerSocket(ws: WebSocket, data: unknown): void {
    try {
      ws.send(JSON.stringify(data))
    } catch (error) {
      console.error('[UserRelay] Failed to send to server socket:', error)
    }
  }

  /**
   * Send message to specific client
   */
  private sendToClient(deviceId: string, data: unknown): void {
    // Find the WebSocket for this device
    try {
      const sockets = this.getWebSocketsByTags(['client', deviceId])
      for (const socket of sockets) {
        try {
          socket.send(JSON.stringify(data))
        } catch (error) {
          console.error(`[UserRelay] Failed to send to ${deviceId}:`, error)
        }
      }
    } catch {
      // getWebSockets failed — hibernation edge case
    }
  }

  /**
   * Broadcast message to all clients
   */
  private broadcastToClients(data: unknown): void {
    const message = JSON.stringify(data)
    let sockets: WebSocket[]
    try {
      sockets = this.ctx.getWebSockets('client')
    } catch {
      return
    }

    for (const socket of sockets) {
      try {
        socket.send(message)
      } catch (error) {
        console.error('[UserRelay] Failed to broadcast:', error)
      }
    }
  }

  /**
   * Get list of connected devices
   */
  private getConnectedDevices(): Array<{
    deviceId: string
    deviceName: string
    connectedAt: number
    lastActivity: number
  }> {
    return Array.from(this.clients.values()).map((c) => ({
      deviceId: c.deviceId,
      deviceName: c.deviceName,
      connectedAt: c.connectedAt,
      lastActivity: c.lastActivity,
    }))
  }
}
